### ISSUE TITLE
not sure is it a bug ?

### ISSUE THREAD

**Issue by AtwoodDuan** [safe-graph/DGFraud-TF2#2]
I put forward a issue first time, and I don't know what the rules are. Please forgive me if I offend you

semiGnn uses the get_negative_sampling function in Utils.py
but i noticed that len(pairs) not equels len(adj_nodelist)
maybe repalacing “for index in range(0, len(adj_nodelist)):” with “for index in range(0, len(pairs)):”  would more correct？

**Comment by AtwoodDuan** [comment]
我看到view_attention函数实现的时候有点困惑。
按照论文可能是 h 点乘 phi，但是代码里面写的element-wise的乘法 h*phi。
是不说我理解错了，如果有回复，我将不胜感激
![image](https://user-images.githubusercontent.com/19813460/122671725-9ebabf00-d1fa-11eb-9c17-b68b3f98e419.png)
根据这个公式：
![image](https://user-images.githubusercontent.com/19813460/122672128-8350b380-d1fc-11eb-84d1-24e4a32dc3a9.png)

**Comment by AtwoodDuan** [comment]
按照论文理解，每一个view下应该都有一个phi，但是在代码实现里却只有一个phi，
是不是我理解错了，如果有回复，我将不胜感激
![image](https://user-images.githubusercontent.com/19813460/122671701-8a76c200-d1fa-11eb-88c9-14f2e07f0f44.png)

**Comment by YingtongDou** [comment]
Thanks for the question. You are correct and I have fixed this issue.

BTW, there are inconsistencies for the node level attention between the SemiGNN paper and the code. I will update in this thread once I fix it.
