### ISSUE TITLE
review features

### ISSUE THREAD

**Issue by vic2ray** [safe-graph/DGFraud-TF2#3]
作者你好！

在您的论文实验部分提到：

> We take the 100-dimension Word2Vec embedding of each review as its feature like previous work

我的理解是对每一个review的文本内容进行Word2Vec得到100维的特征向量

但是在数据集中显示的是45954x32的features稀疏矩阵，也就是每一个review节点有32维特征：

![image](https://user-images.githubusercontent.com/34100368/135050809-763046c6-895c-4090-9633-9fda77bebf61.png)

我很疑惑这32维特征对应的具体含义，是属于review的文本特征还是行为特征？还是都包含？

在YelpCHI原数数据集论文：

> S. Rayana and L. Akoglu. 2015. Collective Opinion Spam Detection: Bridging Review Networks and Metadata. In KDD.

中review特征提取部分包含6个行为特征和10个文本特征，共16维

由于联系论文作者没有取得回复，我不知道原数据中节点特征是怎样的。

希望您能抽空解答，谢谢！

**Comment by vic2ray** [comment]
抱歉，我刚从README中发现了特征提取的出处：

> * features: a sparse matrix of 32-dimension handcrafted features;
> 
> The YelpChi data preprocessing details can be found in our CIKM'20 paper. To get the complete metadata of the Yelp dataset, please email to ytongdou@gmail.com for inquiry.

**Comment by vic2ray** [comment]
I read this from your paper: 

> We take 32 handcrafted features from [29] (25 handcrafted features from [47] resp.) as the raw node features for Yelp (Amazon resp.) dataset. 
> _Enhancing Graph Neural Network-based Fraud Detectors against Camouflaged Fraudsters_

In paper [47] _GCN-Based User Representation Learning for Unifying Robust Recommendation and Fraudster Detection_ 

mentioned that: 

> In a rating system, users’ behavioural footprints are very indicative of their own characteristics. Thus, for user u, we first construct a dense feature vector xu ∈ Rb with each element representing a pre-defined statistical property of u’s behaviors.

which described features for all **users**. 

So I'm so confused what are those 32 demention features really means?

**Comment by YingtongDou** [comment]
Please email me to get the code

**Comment by dndh** [comment]
> I read this from your paper:
> 
> > We take 32 handcrafted features from [29] (25 handcrafted features from [47] resp.) as the raw node features for Yelp (Amazon resp.) dataset.
> > _Enhancing Graph Neural Network-based Fraud Detectors against Camouflaged Fraudsters_
> 
> In paper [47] _GCN-Based User Representation Learning for Unifying Robust Recommendation and Fraudster Detection_
> 
> mentioned that:
> 
> > In a rating system, users’ behavioural footprints are very indicative of their own characteristics. Thus, for user u, we first construct a dense feature vector xu ∈ Rb with each element representing a pre-defined statistical property of u’s behaviors.
> 
> which described features for all **users**.
> 
> So I'm so confused what are those 32 demention features really means?

Excuse me! Did you got or remember the truth of what are those 32 demention features really means?

**Comment by YingtongDou** [comment]
@dndh Please email me (ytongdou@gmail.com) to get the full feature list and preprocessing code
