### ISSUE TITLE
An error in GAS implementation

### ISSUE THREAD

**Issue by Spycsh** [safe-graph/DGFraud-TF2#5]
There seems to be an error in the implementation in Equation (8) in the GAS paper.

In the combination part from line 553 to 561,
```
        #  Combination
        if self.concat:
            user_output = dot(user_output, self.concate_user_weights,
                              sparse=False)
            item_output = dot(item_output, self.concate_item_weights,
                              sparse=False)

            user_output = tf.concat([user_vecs, user_output], axis=1)
            item_output = tf.concat([item_vecs, item_output], axis=1)
```

It seems that user_vecs rather than user_output should be apply to the `dot` function with concat weights, as shown in the equation (8).

**Comment by YingtongDou** [comment]
Hi, thanks for pointing out this bug. I have fixed it and updated the code.
