### ISSUE TITLE
not sure is it an error?

### ISSUE THREAD

**Issue by yijicheng** [safe-graph/DGFraud-TF2#7]
There are two softmax functions on the line 100 and line 104 of SemiGNN.py as below. Does it repeat?
<img width="798" alt="image" src="https://user-images.githubusercontent.com/53086386/155075509-9067a851-67c4-45a0-b109-f35d6c300b97.png">

**Comment by YingtongDou** [comment]
Thanks for reporting the problem! The softmax function at line 100 is redundant and has been removed.
