### ISSUE TITLE
semiGNN example dataset explanation

### ISSUE THREAD

**Issue by yijicheng** [safe-graph/DGFraud-TF2#8]
Could you please explain the example dataset of SemiGNN? SemiGNN is used in heterogenous graph, so I wonder how to distinguish between user nodes and nodes of other type in one adjacency matrix of 'rownetworks'? 
<img width="798" alt="image" src="https://user-images.githubusercontent.com/53086386/155095158-bbf62302-367d-405d-a6f1-3879a178d753.png">

**Comment by YingtongDou** [comment]
The input data of SemiGNN is a multi-view homogeneous graph. The example data represents the same set of nodes (eight nodes) connected by two different views (two adj matrices). For each view, the user nodes are connected by the same type of non-user nodes (see Fig. 1 in the SemiGNN [paper](https://arxiv.org/pdf/2003.01171.pdf)).
